# Generated by Django 5.1.3 on 2024-12-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userportal', '0004_delete_login_delete_user_remove_event_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='amount',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
