# Generated by Django 5.1.3 on 2024-12-06 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userportal', '0005_alter_event_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('technology', 'Technology'), ('concert', 'Concert'), ('family', 'Family'), ('theatre', 'Theatre'), ('sport', 'Sport')], default='concert', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='amount',
            field=models.CharField(max_length=10),
        ),
    ]
