# Generated by Django 5.1.3 on 2024-12-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userportal', '0008_alter_ticket_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
